apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: make
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    params:
    - name: makeTarget
      description: The target to have make run
  outputs:
    results:
    - name: testResults
      format: junit
      path: logs/tests.xml
  steps:
  - name: run-make
    image: ubuntu
    command: ['make']
    args: ['${inputs.params.makeTarget}']

---
apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: integration-test-in-docker
  namespace: default
spec:
  inputs:
    resources:
    - name: workspace
      type: git
    - name: testImage
      type: image
    params:
    - name: testCommand
      description: The command to run on the image
    - name: testArgs
      description: The arguments to pass to the image
  outputs:
    results:
    - name: testResults
      format: junit
      path: integration/logs/tests.xml
  steps:
  - name: runTests
    image: docker
    command: ['${inputs.resources.params.testCommand}']
    args: ['${inputs.resources.params.testArgs}']
    volumeMounts:
    - name: gac
      mountPath: gac.json
    - name: cloudconfig
      mountPath: /root/.config/gcloud
    - name: dockerSocket
      mountPath: /var/run/docker.sock
  volumes:
  - name: gac
    hostPath:
      path: /workspace/config/gac.json
  - name: cloudconfig
    hostPath:
      path: /workspace/config/gcloud
  - name: dockerSocket
    hostPath:
      path: /var/run/docker.sock